// Generated by tools/generate_icon_font.py.  Do not edit.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace xreader
{
namespace gfx
{

static constexpr uint8_t icon_size = 24;
static constexpr uint8_t icon_stride = 3;

enum icon_t : uint8_t
{
    icon_none,
    icon_book,
    icon_bookmark,
    icon_folder,
    icon_description,
    icon_settings,
    icon_delete,
    icon_chevron_right,
    icon_arrow_back,
    icon_arrow_upward,
    icon_light_mode,
    icon_text_fields,
    icon_search,
    icon_info,
    icon_home,
    icon_menu,
    icon_format_align_left,
    icon_format_align_center,
    icon_format_align_right,
    icon_format_align_justify,
    icon_format_line_spacing,
    icon_sync,
    icon_wifi,
    icon_system_update,
    icon_storage,
    icon_list,
    icon_toc,
    icon_bedtime,
    icon_history,
    icon_open_in_new,
    icon_sd_card,
    icon_drive_file_move,
    icon_battery_full,
    icon_schedule,
    icon_check,
    icon_close,
    icon_add,
    icon_edit,
    icon_swap_horiz,
    icon_margin,
    icon_count,
};

struct icon_glyph_t
{
    uint8_t width;
    uint8_t bitmap[72];
};

extern const icon_glyph_t icon_glyphs[icon_count];

} // namespace gfx
} // namespace xreader
