#pragma once

#include "canvas.hpp"
#include "geometry.hpp"

#include <cstddef>
#include <cstdint>
#include <cstring>

/**
 * @brief Bitmap fonts and text layout, ported from `xr_font_t`/`xr_text_*`/
 * `xr_canvas_draw_text*` (include/xr/xr_text.h, src/xr_text.c).
 *
 * Fonts are plain const data (generated by tools/gen_font.py, re-targeted
 * at this struct shape in a later phase), so they live in flash on a
 * microcontroller. Glyph bitmaps are 8-bit alpha. The word-wrap algorithm
 * below is preserved exactly: `reader/session.hpp`'s pagination depends
 * on identical wrap offsets to the old `paginate()` in app/page_reader.c.
 */
namespace text {

/** @brief One glyph's bitmap location and pen metrics within its font. */
struct glyph {
  std::uint32_t offset = 0;  ///< into font::bitmap.
  std::uint8_t w = 0;
  std::uint8_t h = 0;
  std::int8_t x_off = 0;
  std::int8_t y_off = 0;  ///< bitmap position relative to pen/baseline.
  std::uint8_t advance = 0;
};

/** @brief A bitmap font: either a contiguous codepoint range or a sparse sorted table. */
struct font {
  const char* name = nullptr;
  std::uint8_t first = 0;
  std::uint8_t last = 0;
  std::int16_t ascent = 0;
  std::int16_t descent = 0;
  std::int16_t line_height = 0;
  const glyph* glyphs = nullptr;
  const std::uint8_t* bitmap = nullptr;
  const std::uint32_t* codepoints = nullptr;  ///< nullptr for contiguous legacy fonts.
  std::uint16_t glyph_count = 0;
};

/** @brief Horizontal text alignment within a rect. */
enum class align { left, center, right };

namespace detail {

/** @brief Binary-searches `codepoints`, or indexes contiguously; '?' on any miss. */
inline const glyph* glyph_of(const font& f, std::uint32_t codepoint) {
  if (f.codepoints != nullptr && f.glyph_count != 0) {
    int lo = 0;
    int hi = static_cast<int>(f.glyph_count) - 1;
    while (lo <= hi) {
      const int mid = lo + (hi - lo) / 2;
      if (f.codepoints[mid] == codepoint) return &f.glyphs[mid];
      if (f.codepoints[mid] < codepoint) lo = mid + 1;
      else hi = mid - 1;
    }
    codepoint = '?';
  }
  if (codepoint < f.first || codepoint > f.last) codepoint = '?';
  return &f.glyphs[codepoint - f.first];
}

/** @brief Decodes one UTF-8 codepoint from `s`; returns the byte count consumed. */
inline std::size_t utf8_next(const char* s, std::size_t len, std::uint32_t& codepoint) {
  const unsigned char c = static_cast<unsigned char>(s[0]);
  if (c < 0x80) {
    codepoint = c;
    return 1;
  }
  if (c >= 0xc2 && c <= 0xdf && len >= 2 && (static_cast<unsigned char>(s[1]) & 0xc0) == 0x80) {
    codepoint = (static_cast<std::uint32_t>(c & 0x1f) << 6) |
                (static_cast<unsigned char>(s[1]) & 0x3f);
    return 2;
  }
  if (c >= 0xe0 && c <= 0xef && len >= 3 && (static_cast<unsigned char>(s[1]) & 0xc0) == 0x80 &&
      (static_cast<unsigned char>(s[2]) & 0xc0) == 0x80) {
    codepoint = (static_cast<std::uint32_t>(c & 0x0f) << 12) |
                ((static_cast<unsigned char>(s[1]) & 0x3f) << 6) |
                (static_cast<unsigned char>(s[2]) & 0x3f);
    return 3;
  }
  if (c >= 0xf0 && c <= 0xf4 && len >= 4 && (static_cast<unsigned char>(s[1]) & 0xc0) == 0x80 &&
      (static_cast<unsigned char>(s[2]) & 0xc0) == 0x80 &&
      (static_cast<unsigned char>(s[3]) & 0xc0) == 0x80) {
    codepoint = (static_cast<std::uint32_t>(c & 7) << 18) |
                ((static_cast<unsigned char>(s[1]) & 0x3f) << 12) |
                ((static_cast<unsigned char>(s[2]) & 0x3f) << 6) |
                (static_cast<unsigned char>(s[3]) & 0x3f);
    return 4;
  }
  codepoint = '?';
  return 1;
}

}  // namespace detail

/** @brief Pixel width of `s` (NUL-terminated when `len` < 0) rendered in `f`. */
inline int width(const font& f, const char* s, int len = -1) {
  if (len < 0) len = static_cast<int>(std::strlen(s));
  int w = 0;
  for (std::size_t i = 0; i < static_cast<std::size_t>(len);) {
    std::uint32_t cp = 0;
    const std::size_t n = detail::utf8_next(s + i, static_cast<std::size_t>(len) - i, cp);
    w += detail::glyph_of(f, cp)->advance;
    i += n;
  }
  return w;
}

/**
 * @brief Breaks one line of at most `max_w` pixels at a word boundary.
 * Returns the byte count to draw; `next` receives the offset where the
 * following line starts (spaces/newline consumed).
 */
inline std::size_t wrap(const font& f, const char* s, int max_w, std::size_t& next) {
  std::size_t i = 0;
  std::size_t last_space = 0;
  bool have_space = false;
  int w = 0;

  while (s[i] != '\0' && s[i] != '\n') {
    std::uint32_t cp = 0;
    const std::size_t n = detail::utf8_next(s + i, std::strlen(s + i), cp);
    const int a = detail::glyph_of(f, cp)->advance;
    if (w + a > max_w && i > 0) {
      std::size_t end = have_space ? last_space : i;
      std::size_t consumed = end;
      while (s[consumed] == ' ') ++consumed;
      next = consumed;
      while (end > 0 && s[end - 1] == ' ') --end;
      return end;
    }
    if (s[i] == ' ') {
      last_space = i;
      have_space = true;
    }
    w += a;
    i += n;
  }
  next = (s[i] == '\n') ? i + 1 : i;
  return i;
}

/** @brief Total pixel height of `s` word-wrapped to `max_w`. */
inline int measure_height(const font& f, const char* s, int max_w) {
  int lines = 0;
  std::size_t off = 0;
  std::size_t next = 0;
  do {
    wrap(f, s + off, max_w, next);
    off += next;
    ++lines;
  } while (s[off] != '\0');
  return lines * f.line_height;
}

}  // namespace text

namespace canvas {

/** @brief Draws one line of text at (x, y-top-of-line-box); returns the pen x after the text. */
inline int draw_text(surface& c, const text::font& f, int x, int y, const char* s, int len,
                     std::uint8_t g) {
  if (len < 0) len = static_cast<int>(std::strlen(s));
  const int baseline = y + f.ascent;
  for (int i = 0; i < len;) {
    std::uint32_t cp = 0;
    const std::size_t n = text::detail::utf8_next(s + i, static_cast<std::size_t>(len - i), cp);
    const text::glyph* glyph = text::detail::glyph_of(f, cp);
    if (glyph->w != 0 && glyph->h != 0) {
      draw_mask(c, x + glyph->x_off, baseline + glyph->y_off, glyph->w, glyph->h,
                f.bitmap + glyph->offset, glyph->w, g);
    }
    x += glyph->advance;
    i += static_cast<int>(n);
  }
  return x;
}

/** @brief One line, vertically centered in `r`, ellipsized with "..." if too wide. */
inline void draw_text_in(surface& c, const text::font& f, geometry::rect r, const char* s,
                         text::align align, std::uint8_t g) {
  int len = static_cast<int>(std::strlen(s));
  int w = text::width(f, s, len);
  bool ellipsis = false;
  if (w > r.w) {
    const int ew = text::width(f, "...", 3);
    while (len > 0 && w + ew > r.w) {
      --len;
      w -= text::detail::glyph_of(f, static_cast<unsigned char>(s[len]))->advance;
    }
    while (len > 0 && s[len - 1] == ' ') {
      --len;
      w -= text::detail::glyph_of(f, ' ')->advance;
    }
    w += ew;
    ellipsis = true;
  }
  int x = r.x;
  if (align == text::align::center) x = r.x + (r.w - w) / 2;
  else if (align == text::align::right) x = r.x + r.w - w;
  const int y = r.y + (r.h - (f.ascent + f.descent)) / 2;
  x = draw_text(c, f, x, y, s, len, g);
  if (ellipsis) draw_text(c, f, x, y, "...", 3, g);
}

/** @brief Word-wrapped paragraph(s) from the top of `r`. Returns the height used. */
inline int draw_text_wrapped(surface& c, const text::font& f, geometry::rect r, const char* s,
                             text::align align, std::uint8_t g) {
  int y = r.y;
  std::size_t off = 0;
  std::size_t next = 0;
  do {
    const std::size_t n = text::wrap(f, s + off, r.w, next);
    const int w = text::width(f, s + off, static_cast<int>(n));
    int x = r.x;
    if (align == text::align::center) x = r.x + (r.w - w) / 2;
    else if (align == text::align::right) x = r.x + r.w - w;
    draw_text(c, f, x, y, s + off, static_cast<int>(n), g);
    y += f.line_height;
    off += next;
  } while (s[off] != '\0');
  return y - r.y;
}

}  // namespace canvas
