/* Generated by tools/gen_font.py. */
#ifndef XR_FONTS_H
#define XR_FONTS_H
#include "xr/xr_text.h"

extern const xr_font_t xr_font_sans_14;
extern const xr_font_t xr_font_sans_18;
extern const xr_font_t xr_font_sans_bold_18;
extern const xr_font_t xr_font_sans_bold_26;
extern const xr_font_t xr_font_serif_17;
extern const xr_font_t xr_font_serif_20;
extern const xr_font_t xr_font_serif_24;
extern const xr_font_t xr_font_alegreya_14;
extern const xr_font_t xr_font_alegreya_18;
extern const xr_font_t xr_font_alegreya_bold_18;
extern const xr_font_t xr_font_alegreya_bold_26;
extern const xr_font_t xr_font_alegreya_17;
extern const xr_font_t xr_font_alegreya_20;
extern const xr_font_t xr_font_alegreya_24;


#endif
