/* Generated by tools/generate_icon_font.py. */
#ifndef XR_ICONS_H
#define XR_ICONS_H
#include <stdint.h>

enum xr_icon {
    XR_ICON_NONE,
    XR_ICON_BOOK,
    XR_ICON_FOLDER,
    XR_ICON_DESCRIPTION,
    XR_ICON_SETTINGS,
    XR_ICON_DELETE,
    XR_ICON_ARROW_BACK,
    XR_ICON_SEARCH,
    XR_ICON_INFO,
    XR_ICON_TEXT_FIELDS,
    XR_ICON_REMOVE,
    XR_ICON_SD_CARD,
    XR_ICON_CLOSE,
    XR_ICON_ADD,
    XR_ICON_COUNT
};
typedef struct xr_icon_glyph { uint8_t width; uint8_t bitmap[72]; } xr_icon_glyph_t;
extern const xr_icon_glyph_t xr_icons[XR_ICON_COUNT];
#endif
