#!/usr/bin/env python3
import argparse
from pathlib import Path
import re


def parse_config(path: Path):
    enabled = set()
    if path.exists():
        for raw in path.read_text(encoding='utf-8').splitlines():
            line = raw.strip()
            m = re.fullmatch(r'CONFIG_PLUGIN_([A-Z0-9_]+)=y', line)
            if m:
                enabled.add(m.group(1))
    return enabled


def symbol(name: str) -> str:
    return re.sub(r'[^A-Za-z0-9]', '_', name).upper()


def ns(name: str) -> str:
    value = re.sub(r'[^A-Za-z0-9_]', '_', name)
    if value and value[0].isdigit():
        value = '_' + value
    return value


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--plugins', default='plugins')
    ap.add_argument('--config', default='.config')
    ap.add_argument('--out', default='build/generated')
    ap.add_argument('--enable', default='')
    args = ap.parse_args()

    root = Path(args.plugins)
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    discovered = []
    if root.exists():
        for child in sorted(p for p in root.iterdir() if p.is_dir() and not p.name.startswith('.')):
            cpp = child / 'cpp' / 'init.hpp'
            lua = child / 'lua' / 'init.lua'
            kconfig = child / 'Kconfig'
            if cpp.exists() or lua.exists() or kconfig.exists():
                discovered.append((child.name, cpp.exists(), lua.exists(), kconfig.exists()))

    enabled = parse_config(Path(args.config))
    for item in args.enable.split():
        enabled.add(symbol(item))

    selected = [item for item in discovered if symbol(item[0]) in enabled]

    kconfig_lines = ['# Generated by scripts/gen_plugins.py. Do not edit.']
    for name, _, _, has_kconfig in discovered:
        if has_kconfig:
            kconfig_lines.append(f'source "plugins/{name}/Kconfig"')
    (out / 'plugins.Kconfig').write_text('\n'.join(kconfig_lines) + '\n', encoding='utf-8')

    config_lines = [
        '#pragma once',
        '',
        '// Generated by scripts/gen_plugins.py. Do not edit.',
    ]
    for name, *_ in selected:
        config_lines.append(f'#define CONFIG_PLUGIN_{symbol(name)} 1')
    config_lines.append('')
    (out / 'plugin_config.hpp').write_text('\n'.join(config_lines), encoding='utf-8')

    cpp_lines = [
        '#pragma once',
        '',
        '// Generated by scripts/gen_plugins.py. Do not edit.',
        '#include "plugin_config.hpp"',
    ]
    for name, has_cpp, _, _ in selected:
        if has_cpp:
            macro = f'CONFIG_PLUGIN_{symbol(name)}'
            cpp_lines += [f'#if defined({macro})', f'#include "plugins/{name}/cpp/init.hpp"', '#endif']
    cpp_lines += [
        '',
        'namespace generated::plugins {',
        'template <typename Context>',
        'inline bool init(Context& ctx) {',
        '  bool ok = true;',
        '  (void)ctx;',
    ]
    for name, has_cpp, _, _ in selected:
        if has_cpp:
            macro = f'CONFIG_PLUGIN_{symbol(name)}'
            cpp_lines += [f'#if defined({macro})', f'  ok = ::plugins::{ns(name)}::init(ctx) && ok;', '#endif']
    cpp_lines += ['  return ok;', '}', '}  // namespace generated::plugins', '']
    (out / 'enabled_plugins.hpp').write_text('\n'.join(cpp_lines), encoding='utf-8')

    lua_modules = [f'plugins.{name}.lua.init' for name, _, has_lua, _ in selected if has_lua]
    lua_lines = [
        '-- Generated by scripts/gen_plugins.py. Do not edit.',
        'local M = {}',
        'local modules = {',
    ]
    lua_lines += [f'    "{module}",' for module in lua_modules]
    lua_lines += [
        '}',
        '',
        'function M.init()',
        '    for _, name in ipairs(modules) do',
        '        local plugin = require(name)',
        '        if plugin.init and plugin.init() == false then return false end',
        '    end',
        '    return true',
        'end',
        '',
        'function M.modules()',
        '    return modules',
        'end',
        '',
        'return M',
        '',
    ]
    (out / 'enabled_plugins.lua').write_text('\n'.join(lua_lines), encoding='utf-8')

    mk_lines = ['# Generated by scripts/gen_plugins.py. Do not edit.']
    mk_lines.append('ENABLED_PLUGINS := ' + ' '.join(name for name, *_ in selected))
    (out / 'plugins.mk').write_text('\n'.join(mk_lines) + '\n', encoding='utf-8')

    print('plugins: discovered=' + ','.join(name for name, *_ in discovered))
    print('plugins: enabled=' + ','.join(name for name, *_ in selected))


if __name__ == '__main__':
    main()
