/*
 * xr_text.h - bitmap fonts and text layout.
 *
 * Fonts are plain const data (generated by tools/gen_font.py), so they
 * live in flash on a microcontroller. Glyph bitmaps are 8-bit alpha.
 * Currently ASCII 32..126; see README for the UTF-8 / Vietnamese plan.
 */
#ifndef XR_TEXT_H
#define XR_TEXT_H

#include "xr_canvas.h"

typedef struct xr_glyph {
    uint32_t offset;     /* into font->bitmap */
    uint8_t w, h;        /* bitmap size */
    int8_t x_off, y_off; /* bitmap position relative to pen/baseline */
    uint8_t advance;
} xr_glyph_t;

typedef struct xr_font {
    const char *name;
    uint8_t first, last;
    int16_t ascent, descent, line_height;
    const xr_glyph_t *glyphs;
    const uint8_t *bitmap;
} xr_font_t;

typedef enum xr_align { XR_ALIGN_LEFT, XR_ALIGN_CENTER, XR_ALIGN_RIGHT } xr_align_t;

/* len < 0 means NUL-terminated. */
int xr_text_width(const xr_font_t *f, const char *s, int len);

/*
 * Breaks one line of at most max_w pixels at a word boundary.
 * Returns the number of bytes to draw; *next receives the offset where
 * the following line starts (spaces / newline consumed).
 */
size_t xr_text_wrap(const xr_font_t *f, const char *s, int max_w, size_t *next);

int xr_text_measure_height(const xr_font_t *f, const char *s, int max_w);

/* y is the top of the line box. Returns the pen x after the text. */
int xr_canvas_draw_text(xr_canvas_t *c, const xr_font_t *f, int x, int y,
                        const char *s, int len, uint8_t gray);

/* One line, vertically centred in r, ellipsized with "..." if too wide. */
void xr_canvas_draw_text_in(xr_canvas_t *c, const xr_font_t *f, xr_rect_t r,
                            const char *s, xr_align_t align, uint8_t gray);

/* Word-wrapped paragraph(s) from the top of r. Returns the height used. */
int xr_canvas_draw_text_wrapped(xr_canvas_t *c, const xr_font_t *f, xr_rect_t r,
                                const char *s, xr_align_t align, uint8_t gray);

#endif /* XR_TEXT_H */
