#!/usr/bin/env python3
"""Rasterize TrueType fonts into xr_font_t C sources (ASCII 32..126, 8-bit alpha).

Usage: python3 tools/gen_font.py [out_dir]
Edit FONTS to change faces/sizes. Output is plain const data: on a
microcontroller it stays in flash.
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFont

DEJAVU_DIR = "/usr/share/fonts/truetype/dejavu/"
ALEGREYA_DIR = os.environ.get("ALEGREYA_FONT_DIR", "/usr/share/fonts/truetype/alegreya/")

# (C name, font file, pixel size, extra leading)
FONTS = [
    ("sans_14", os.path.join(DEJAVU_DIR, "DejaVuSans.ttf"), 14, 3),
    ("sans_18", os.path.join(DEJAVU_DIR, "DejaVuSans.ttf"), 18, 4),
    ("sans_bold_18", os.path.join(DEJAVU_DIR, "DejaVuSans-Bold.ttf"), 18, 4),
    ("sans_bold_26", os.path.join(DEJAVU_DIR, "DejaVuSans-Bold.ttf"), 26, 4),
    ("serif_17", os.path.join(DEJAVU_DIR, "DejaVuSerif.ttf"), 17, 8),
    ("serif_20", os.path.join(DEJAVU_DIR, "DejaVuSerif.ttf"), 20, 9),
    ("serif_24", os.path.join(DEJAVU_DIR, "DejaVuSerif.ttf"), 24, 10),
    ("alegreya_14", os.path.join(ALEGREYA_DIR, "Alegreya-Regular.ttf"), 14, 3),
    ("alegreya_18", os.path.join(ALEGREYA_DIR, "Alegreya-Regular.ttf"), 18, 4),
    ("alegreya_bold_18", os.path.join(ALEGREYA_DIR, "Alegreya-Bold.ttf"), 18, 4),
    ("alegreya_bold_26", os.path.join(ALEGREYA_DIR, "Alegreya-Bold.ttf"), 26, 4),
    ("alegreya_17", os.path.join(ALEGREYA_DIR, "Alegreya-Regular.ttf"), 17, 8),
    ("alegreya_20", os.path.join(ALEGREYA_DIR, "Alegreya-Regular.ttf"), 20, 9),
    ("alegreya_24", os.path.join(ALEGREYA_DIR, "Alegreya-Regular.ttf"), 24, 10),
]

UNICODE_RANGES = ((0x0020, 0x007E), (0x00A0, 0x00FF), (0x0100, 0x024F),
                  (0x0300, 0x036F), (0x1E00, 0x1EFF))


def gen(name, file, size, leading):
    font = ImageFont.truetype(file, size)
    ascent, descent = font.getmetrics()
    glyphs, bitmap = [], bytearray()
    codepoints = [code for first, last in UNICODE_RANGES for code in range(first, last + 1)]
    for code in codepoints:
        ch = chr(code)
        l, t, r, b = font.getbbox(ch, anchor="ls")
        w, h = max(0, r - l), max(0, b - t)
        off = len(bitmap)
        if w and h:
            im = Image.new("L", (w, h), 0)
            ImageDraw.Draw(im).text((-l, -t), ch, font=font, fill=255, anchor="ls")
            bitmap += im.tobytes()
        glyphs.append((off, w, h, l, t, round(font.getlength(ch))))

    out = [f"/* Generated by tools/gen_font.py from {os.path.basename(file)} @ {size}px. Do not edit. */",
           '#include "xr_fonts.h"', "",
           f"static const uint8_t k_bitmap[{max(len(bitmap), 1)}] = {{"]
    data = bitmap or b"\0"
    for i in range(0, len(data), 24):
        out.append("    " + ",".join(str(v) for v in data[i:i + 24]) + ",")
    out.append("};\n")
    out.append(f"static const xr_glyph_t k_glyphs[{len(codepoints)}] = {{")
    for code, g in zip(codepoints, glyphs):
        out.append("    {%d, %d, %d, %d, %d, %d}, /* %r */" % (g + (chr(code),)))
    out.append("};\n")
    out.append(f"static const uint32_t k_codepoints[{len(codepoints)}] = {{")
    for code in codepoints:
        out.append(f"    0x{code:04x},")
    out.append("};\n")
    out.append(f"const xr_font_t xr_font_{name} = {{")
    out.append(f'    "{os.path.splitext(os.path.basename(file))[0]} {size}", 32, 126, {ascent}, {descent}, '
               f"{ascent + descent + leading}, k_glyphs, k_bitmap, k_codepoints, {len(codepoints)}")
    out.append("};")
    return "\n".join(out) + "\n", len(bitmap)


def main():
    out_dir = sys.argv[1] if len(sys.argv) > 1 else "fonts"
    os.makedirs(out_dir, exist_ok=True)
    only = set(filter(None, os.environ.get("XR_FONT_ONLY", "").split(",")))
    header = ["/* Generated by tools/gen_font.py. */", "#ifndef XR_FONTS_H", "#define XR_FONTS_H",
               '#include "xr/xr_text.h"', ""]
    for name, file, size, leading in FONTS:
        header.append(f"extern const xr_font_t xr_font_{name};")
    header.append("")
    for name, file, size, leading in FONTS:
        if only and name not in only:
            continue
        src, nbytes = gen(name, file, size, leading)
        with open(os.path.join(out_dir, f"xr_font_{name}.c"), "w") as f:
            f.write(src)
        print(f"xr_font_{name}: {nbytes} bytes")
    header += ["", "#endif", ""]
    with open(os.path.join(out_dir, "xr_fonts.h"), "w") as f:
        f.write("\n".join(header))


if __name__ == "__main__":
    main()
