#!/usr/bin/env python3
"""Generate the 1-bpp icon glyph table from the Material Symbols variable font.

Mirrors generate_unicode_font.py: the font is rasterised at build-authoring time
and the result is checked in, so the firmware carries a plain C table and no
font dependency.

The icon list below is the single source of truth.  Both the `icon_t` enum
header and the glyph table are generated from it, so a name and its bitmap
cannot drift apart.

Usage:
    generate_icon_font.py MATERIAL_SYMBOLS.ttf main/gfx
"""

import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

# Icon box is square and byte-aligned so a row is a whole number of bytes.
SIZE = 24
STRIDE = SIZE // 8

# (enum suffix, Material Symbols codepoint).  Names are the upstream icon names
# so they can be looked up at fonts.google.com/icons.
ICONS = [
    ("none", None),
    ("book", 0xE865),
    ("bookmark", 0xE866),
    ("folder", 0xE2C7),
    ("description", 0xE873),
    ("settings", 0xE8B8),
    ("delete", 0xE872),
    ("chevron_right", 0xE5CC),
    ("arrow_back", 0xE5C4),
    ("arrow_upward", 0xE5D8),
    ("light_mode", 0xE518),
    ("text_fields", 0xE262),
    ("search", 0xE8B6),
    ("info", 0xE88E),
    ("home", 0xE88A),
    ("menu", 0xE5D2),
    ("format_align_left", 0xE236),
    ("format_align_center", 0xE234),
    ("format_align_right", 0xE237),
    ("format_align_justify", 0xE235),
    ("format_line_spacing", 0xE240),
    ("sync", 0xE627),
    ("wifi", 0xE63E),
    ("system_update", 0xE8D7),
    ("storage", 0xE1DB),
    ("list", 0xE896),
    ("toc", 0xE8DE),
    ("bedtime", 0xEF44),
    ("history", 0xE889),
    ("open_in_new", 0xE89E),
    ("sd_card", 0xE623),
    ("drive_file_move", 0xE675),
    ("battery_full", 0xE1A4),
    ("schedule", 0xE8B5),
    ("check", 0xE5CA),
    ("close", 0xE5CD),
    ("add", 0xE145),
    ("edit", 0xE3C9),
    ("swap_horiz", 0xE8D4),
    ("margin", 0xE9E4),
]


def render(font, codepoint):
    """Return (ink_width, packed_rows) for one glyph, or None when blank."""
    image = Image.new("L", (SIZE, SIZE), 0)
    draw = ImageDraw.Draw(image)
    # Material Symbols sit on the baseline with the icon box filling the em, so
    # anchoring the baseline at the bottom of a SIZE-tall box centres the glyph.
    draw.text((0, SIZE), chr(codepoint), font=font, fill=255, anchor="ls")

    rows = []
    right = 0
    for y in range(SIZE):
        packed = [0] * STRIDE
        for x in range(SIZE):
            if image.getpixel((x, y)) >= 128:
                packed[x // 8] |= 1 << (7 - (x % 8))
                right = max(right, x + 1)
        rows.extend(packed)
    return right, rows


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: generate_icon_font.py FONT OUTPUT_DIR")
    font_path = sys.argv[1]
    output_dir = Path(sys.argv[2])

    font = ImageFont.truetype(font_path, SIZE)
    # FILL=100 gives the solid glyphs the mockup uses; a stroke-only outline
    # loses too much at 24 px once thresholded to one bit.
    font.set_variation_by_axes([100.0, 0.0, float(SIZE), 500.0])

    names = [name for name, _ in ICONS]
    header = [
        "// Generated by tools/generate_icon_font.py.  Do not edit.",
        "#pragma once",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "namespace xreader",
        "{",
        "namespace gfx",
        "{",
        "",
        f"static constexpr uint8_t icon_size = {SIZE};",
        f"static constexpr uint8_t icon_stride = {STRIDE};",
        "",
        "enum icon_t : uint8_t",
        "{",
    ]
    header.extend(f"    icon_{name}," for name in names)
    header.extend(
        [
            "    icon_count,",
            "};",
            "",
            "struct icon_glyph_t",
            "{",
            "    uint8_t width;",
            f"    uint8_t bitmap[{SIZE * STRIDE}];",
            "};",
            "",
            "extern const icon_glyph_t icon_glyphs[icon_count];",
            "",
            "} // namespace gfx",
            "} // namespace xreader",
            "",
        ]
    )
    (output_dir / "icon_font.hpp").write_text("\n".join(header), encoding="ascii")

    table = [
        "// Generated by tools/generate_icon_font.py.  Do not edit.",
        "// Glyphs from Material Symbols, Apache-2.0; see MaterialSymbols-LICENSE.txt.",
        "#include \"icon_font.hpp\"",
        "",
        "namespace xreader",
        "{",
        "namespace gfx",
        "{",
        "",
        "const icon_glyph_t icon_glyphs[icon_count] = {",
    ]
    blank = ", ".join("0x00" for _ in range(SIZE * STRIDE))
    for name, codepoint in ICONS:
        if codepoint is None:
            table.append(f"    {{0, {{{blank}}}}}, // icon_{name}")
            continue
        width, rows = render(font, codepoint)
        if width == 0:
            raise SystemExit(f"glyph for {name} (U+{codepoint:04X}) rendered blank")
        values = ", ".join(f"0x{value:02x}" for value in rows)
        table.append(f"    {{{width}, {{{values}}}}}, // icon_{name} U+{codepoint:04X}")
    table.extend(
        [
            "};",
            "",
            "} // namespace gfx",
            "} // namespace xreader",
            "",
        ]
    )
    (output_dir / "icon_font.cpp").write_text("\n".join(table), encoding="ascii")
    print(f"wrote {len(ICONS)} icons to {output_dir}")


if __name__ == "__main__":
    main()
