#!/usr/bin/env python3
"""Generate the C99 1-bpp icon table from Material Symbols."""
import sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

SIZE = 24
STRIDE = 3
ICONS = [("none", None), ("book", 0xE865), ("folder", 0xE2C7),
         ("description", 0xE873), ("settings", 0xE8B8), ("delete", 0xE872),
         ("arrow_back", 0xE5C4), ("search", 0xE8B6), ("info", 0xE88E),
         ("text_fields", 0xE262), ("remove", 0xE15B), ("sd_card", 0xE623),
         ("close", 0xE5CD), ("add", 0xE145)]

def render(font, cp):
    image = Image.new("L", (SIZE, SIZE), 0)
    ImageDraw.Draw(image).text((0, SIZE), chr(cp), font=font, fill=255, anchor="ls")
    rows, right = [], 0
    for y in range(SIZE):
        packed = [0] * STRIDE
        for x in range(SIZE):
            if image.getpixel((x, y)) >= 128:
                packed[x // 8] |= 1 << (7 - x % 8)
                right = max(right, x + 1)
        rows.extend(packed)
    return right, rows

def main():
    if len(sys.argv) != 3: raise SystemExit("usage: generate_icon_font.py FONT OUTPUT_DIR")
    font = ImageFont.truetype(sys.argv[1], SIZE)
    font.set_variation_by_axes([100.0, 0.0, float(SIZE), 500.0])
    out = Path(sys.argv[2])
    header = ["/* Generated by tools/generate_icon_font.py. */", "#ifndef XR_ICONS_H", "#define XR_ICONS_H", "#include <stdint.h>", "", "enum xr_icon {"]
    header += [f"    XR_ICON_{name.upper()}," for name, _ in ICONS] + ["    XR_ICON_COUNT", "};", "typedef struct xr_icon_glyph { uint8_t width; uint8_t bitmap[72]; } xr_icon_glyph_t;", "extern const xr_icon_glyph_t xr_icons[XR_ICON_COUNT];", "#endif", ""]
    (out / "xr_icons.h").write_text("\n".join(header), encoding="ascii")
    lines = ["/* Generated by tools/generate_icon_font.py. */", '#include "xr_icons.h"', "", "const xr_icon_glyph_t xr_icons[XR_ICON_COUNT] = {"]
    blank = ", ".join(["0"] * 72)
    for name, cp in ICONS:
        if cp is None: width, pixels = 0, [0] * 72
        else: width, pixels = render(font, cp)
        lines.append("    {%d, {%s}}, /* %s */" % (width, ", ".join(str(x) for x in pixels), name))
    lines += ["};", ""]
    (out / "xr_icons.c").write_text("\n".join(lines), encoding="ascii")

if __name__ == "__main__": main()
